### ISSUE TITLE
Keep gdu open when spawning shell

### ISSUE THREAD

**Issue by Tungstwenty** [dundee/gdu#90]
I use the new 'b' shortcut to quickly open a shell on a folder that is of interest to me and it's very useful.
One thing I think could be improved is if the shell would be opened without killing gdu, so that after exiting the shell I would still have all the data loaded, the same folder selected, etc. in order to investigate the next problematic folder and so on.
Much like the way you can user "! ..." in vi to spawn a shell and resume where you were once the shell ends.

**Comment by dundee** [comment]
Unfortunately I wasn't able to implement this with the current terminal library (https://github.com/rivo/tview). There is possibility to pause the interface of the application, but it was not working for me properly, the user interface froze after returning back from shell.

**Comment by Tungstwenty** [comment]
Did you have a look at this issue on their tracker? https://github.com/rivo/tview/issues/244
There's some reproducer code there and indication that the issue is now fixed (if it's the same, that is)

**Comment by dundee** [comment]
Thanks for link, I will try to investigate more.

**Comment by rashil2000** [comment]
> ...but it was not working for me properly, the user interface froze after returning back from shell.

Hi @dundee 

I ran the latest build v5.7.0 (on Windows) but I'm still facing this, the UI hangs after exiting the shell.

**Comment by dundee** [comment]
> > ...but it was not working for me properly, the user interface froze after returning back from shell.
> 
> Hi @dundee
> 
> I ran the latest build v5.7.0 (on Windows) but I'm still facing this, the UI hangs after exiting the shell.

Thanks, I will try to investigate it.
